config/routes.rb
Rails.application.routes.draw do
  get 'api/news', to: 'api#index'
  get 'api/:start_date/:end_date', to: 'api#by_date'
  post 'api/tweets', to: 'api#create'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root 'tweets#index'
  get 'tweets/friends'
  get 'tweets/followers'
  get '/tweets/hashtag/:name', to: 'tweets#hashtags'

  resources :tweets do
    post 'like', to:'tweets#like'
    post 'retweet', to:'tweets@retweet'
    post :friend
  end
end

app/views/shared/_alert.html.erb
    <% if notice  %>
    <div class ="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>Información</h4>
            <p><%= notice %></p>
    </div>
    <% end %>

    <% if alert  %>
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>Atención</h4>
        <p><%= alert %></p>
    </div>
    <% end %>

app/views/shared/_content_tweet.html.erb
    <% if current_user %>
    <h3><%= "Welcome #{current_user.name}!"%></h3>
    <br>
    <%= render 'form', tweet: @tweet %>
    <% else  %>
    <br>
    <h2><%= link_to "New here? Join Us!", new_user_registration_path %></h2>
    <% end %>
    <br> 
    <br>


    <% @tweets.each do |tweet| %>

    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
        <div class="col-md-4">
        <%= image_tag(tweet.user.photo_avatar, width: "50%") %>
        <br>
        <td><%= tweet.html_content(tweet.content) %></td>
        <td><%= tweet.user.name %>
        <% if current_user %>
            <% if current_user.friends.pluck(:follower_id).include?(tweet.user.id) %>

            <%= link_to 'UnFollow', tweet_unfollower_path(tweet), method: :delete %>

            <% elsif current_user.id == tweet.user.id %>
        
            <% else %>
                <%= link_to 'Follow', tweet_friend_path(tweet), method: :post %>
            <% end %>
        
        <% else %>

        <% end %>
        </td>

        </div>
        <div class="col-md-8">
            <div class="card-body">
            <% if tweet.origin_tweet.nil? %>
            <p class="card-text"><%= tweet.content%></p>
            <% else %>
            <%= image_tag(tweet.original_tweet.user.photo_avatar, width: "50%")%> 
            <%= tweet.original_tweet.user.name %> 
            <div class= "container mx-auto">
            <%= tweet.content %>
            </div>
            <% end %>
            <%= link_to 'like', tweet_like_path(tweet), method: :post %>
            <%= tweet.likes.count %>
            <%= link_to 'retweet', tweet_retweet_path(tweet), method: :post %>

            <%= link_to tweet_path(tweet) do %>
                <small><%= time_ago_in_words(tweet.created_at) %> ago</small>
                <% end %> 
            </div>
        </div>
        </div>
    </div>
    <% end %>
    

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Twitter Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% if user_signed_in? %>
                <li><%= link_to 'My Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
                <% end %>
            </ul>
            </li>
        </ul>
        </div>
    </div>
    </nav>